"""Add User, Store and encrypted Token

Revision ID: 66eb87710b63
Revises: 
Create Date: 2025-12-31 16:54:51.173062

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '66eb87710b63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tiendanube_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_tiendanube_user_id'), 'store', ['tiendanube_user_id'], unique=True)
    op.add_column('tiendanubetoken', sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tiendanubetoken', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'tiendanubetoken', ['user_id'])
    op.create_foreign_key(None, 'tiendanubetoken', 'store', ['store_id'], ['id'])
    op.drop_column('tiendanubetoken', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiendanubetoken', sa.Column('access_token', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'tiendanubetoken', type_='foreignkey')
    op.drop_constraint(None, 'tiendanubetoken', type_='unique')
    op.drop_column('tiendanubetoken', 'store_id')
    op.drop_column('tiendanubetoken', 'access_token_encrypted')
    op.drop_index(op.f('ix_store_tiendanube_user_id'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
