"""fix_token_constraints

Revision ID: b91219ed8db7
Revises: 1d2f6c0cbe93
Create Date: 2026-01-01 11:33:36.311593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
"""fix_token_constraints

Revision ID: b91219ed8db7
Revises: 1d2f6c0cbe93
Create Date: 2026-01-01 11:33:36.311593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b91219ed8db7'
down_revision = '1d2f6c0cbe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiendanubetoken', schema=None) as batch_op:
        # Only attempt to drop named constraint on Postgres where we know it exists.
        # SQLite doesn't track names the same way and batch mode fails if verification fails.
        if op.get_context().dialect.name == 'postgresql':
             batch_op.drop_constraint('tiendanubetoken_user_id_key', type_='unique')
        
        # We always want the new constraint
        batch_op.create_unique_constraint('uq_tiendanubetoken_store_id', ['store_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tiendanubetoken', type_='unique')
    # ### end Alembic commands ###
