"""fix_token_constraints

Revision ID: b91219ed8db7
Revises: 1d2f6c0cbe93
Create Date: 2026-01-01 11:33:36.311593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
"""fix_token_constraints

Revision ID: b91219ed8db7
Revises: 1d2f6c0cbe93
Create Date: 2026-01-01 11:33:36.311593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b91219ed8db7'
down_revision = '1d2f6c0cbe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old unique constraint on user_id (allowing duplicates for historical/admin reasons)
    # Note: If running on SQLite, this might require batch_alter_table. Postgres is fine.
    try:
        op.drop_constraint('tiendanubetoken_user_id_key', 'tiendanubetoken', type_='unique')
    except Exception:
        # Fallback if name is different or sqlite (though user is on Postgres)
        pass
        
    op.create_unique_constraint(None, 'tiendanubetoken', ['store_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tiendanubetoken', type_='unique')
    # ### end Alembic commands ###
