"""add user_session model

Revision ID: c0a1b2c3d4e5
Revises: b91219ed8db7
Create Date: 2026-01-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'c0a1b2c3d4e5'
down_revision = 'b91219ed8db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersession',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token_hash', sa.VARCHAR(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersession_token_hash'), 'usersession', ['token_hash'], unique=True)
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_token_hash'), table_name='usersession')
    op.drop_table('usersession')
    # ### end Alembic commands ###
